import pyautogui,time

pyautogui.press('win')
time.sleep(1)
pyautogui.typewrite('windows security')
time.sleep(1)
pyautogui.press('enter')
time.sleep(3)
pyautogui.press('left')
time.sleep(1)
pyautogui.press('up')
time.sleep(1)
pyautogui.press('enter')
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.press('space')
time.sleep(2)
pyautogui.press('left')
time.sleep(1)
pyautogui.press('enter')
